name: Scan PowerShell Code

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  # Required to upload results to the Security tab
  security-events: write

jobs:
  analyze:
    name: Run PSScriptAnalyzer Scan
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Run PSScriptAnalyzer and create SARIF
        shell: pwsh
        run: |
          # Install the required modules
          Install-Module -Name PSScriptAnalyzer -Force
          Install-Module -Name Microsoft.CodeAnalysis.Sarif.PowerShell -Force
          
          $sarifFile = "psscriptanalyzer-results.sarif"
          
          # Run the analyzer and pipe the results to the SARIF converter.
          # We use '-ErrorAction SilentlyContinue' to ensure the script
          # ALWAYS continues, even when it finds errors.
          Invoke-ScriptAnalyzer -Path ${{ github.workspace }} -Recurse -ErrorAction SilentlyContinue | ConvertTo-SarifLog -OutputFile $sarifFile -ErrorAction SilentlyContinue
          
          Write-Host "Scan complete. SARIF file generated."

      - name: Upload SARIF to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          # Path to the file generated by the previous step
          sarif_file: 'psscriptanalyzer-results.sarif'
          
          # A unique category name for this tool
          category: 'PSScriptAnalyzer'
